### PR TITLE
LCM scripts refactor

### LINKED ISSUE #93: CEE LAN build fails because it can't find YAML
Using the LCM environment tools I do the following:

% source Albany/doc/LCM/build/modules-sems.sh
% module load serial-gcc-release
% ./clean-config-build.sh trilinos 20

I get the following:

(...configuration stuff...)
Processing enabled TPL: yaml-cpp (enabled explicitly, disable with -DTPL_ENABLE_yaml-cpp=OFF)
-- Searching for libs in yaml-cpp_LIBRARY_DIRS=''
-- Searching for a lib in the set "yaml-cpp":
--   Searching for lib 'yaml-cpp' ...
-- ERROR: Did not find a lib in the lib set "yaml-cpp" for the TPL 'yaml-cpp'!
-- ERROR: Could not find the libraries for the TPL 'yaml-cpp'!
-- TIP: If the TPL 'yaml-cpp' is on your system then you can set:
     -Dyaml-cpp_LIBRARY_DIRS='<dir0>;<dir1>;...'
   to point to the directories where these libraries may be found.
   Or, just set:
     -DTPL_yaml-cpp_LIBRARIES='<path-to-libs0>;<path-to-libs1>;...'
   to point to the full paths for the libraries which will
   bypass any search for libraries and these libraries will be used without
   question in the build.  (But this will result in a build-time error
   if not all of the necessary symbols are found.)
-- ERROR: Failed finding all of the parts of TPL 'yaml-cpp' (see above), Aborting!

-- NOTE: The find module file for this failed TPL 'yaml-cpp' is:
     /gpfs1/jtostie/LCM/Trilinos/cmake/TPLs/FindTPLyaml-cpp.cmake
   which is pointed to in the file:
     /gpfs1/jtostie/LCM/Trilinos/TPLsList.cmake

TIP: Even though the TPL 'yaml-cpp' was explicitly enabled in input,
it can be disabled with:
  -DTPL_ENABLE_yaml-cpp=OFF
which will disable it and will recursively disable all of the
downstream packages that have required dependencies on it.
When you reconfigure, just grep the cmake stdout for 'yaml-cpp'
and then follow the disables that occur as a result to see what impact
this TPL disable has on the configuration of Trilinos.

CMake Error at cmake/tribits/core/package_arch/TribitsProcessEnabledTpl.cmake:127 (MESSAGE):
  ERROR: TPL_yaml-cpp_NOT_FOUND=TRUE, aborting!
Call Stack (most recent call first):
  cmake/tribits/core/package_arch/TribitsGlobalMacros.cmake:1644 (TRIBITS_PROCESS_ENABLED_TPL)
  cmake/tribits/core/package_arch/TribitsProjectImpl.cmake:202 (TRIBITS_PROCESS_ENABLED_TPLS)
  cmake/tribits/core/package_arch/TribitsProject.cmake:93 (TRIBITS_PROJECT_IMPL)
  CMakeLists.txt:93 (TRIBITS_PROJECT)

### PR DESCRIPTION
**Pull request by ibaned**
This refactor does several things:

1. Resolves #93 
2. Replaces `modules-sems.sh` with a module `lcm/sems`
3. Makes `cee_serial-gcc-*.sh` obsolete, all the modules can now be used on both platforms
4. Combines lots of redundant code into small orthogonal submodules in `modulefiles/lcm/`

The new way to use the modules is like this:

```bash
module load lcm/sems
module load serial-gcc-release
./clean-config-build.sh trilinos 16
```

If you are on the fedora systems, just load `lcm/fedora` instead of `lcm/sems`.

@lxmota @jtostie @calleman21

### CODE REVIEW

**Comment by ibaned** [comment]
Since @lxmota  has added commits to update the documentation, I assume he approves. I'll go ahead and merge this.

**Comment by lxmota** [comment]
I was just waiting for the SEMS build to finish to approve this, but everything seems to be OK.

It's just that the build is so slow in the machine I'm using.

**Comment by jwfoulk** [comment]
Greetings everyone,

Thank you for pushing on the sems builds. It couldn't be easier. 

One of the tests fails on the CEE Lan - SurfaceElementLocking - because algebra cannot be executed. The reason is that the system libraries come before the libraries used to compile trilinos. I think the Fedora build relies on this but this will lead to issues on the CEE lan and building for the clusters.  For example, I get the following error after loading sems and serial-gcc-release:

[jwfoulk@ceerws2210 SurfaceElementLocking]$ algebra outNoVolJ.e outNoVolJ.alg.e
algebra: symbol lookup error: /usr/lib64/openmpi/lib/libmpi.so.1: undefined symbol: opal_memchecker_base_isdefined

algebra is in LCM/trilinos-install-serial-gcc-release/bin/algebra

There are multiple shared object libraries in my path - that resulted from the gcc-serial-release module. 

jwfoulk@ceerws2210 SurfaceElementLocking]$ echo $LD_LIBRARY_PATH
/usr/local/netcdf/lib:/usr/lib64/openmpi/lib:/scratch/jwfoulk/builds/LCM/trilinos-install-serial-gcc-release/lib:/projects/sems/install/rhel6-x86_64/sems/tpl/yaml_cpp/0.5.3/gcc/6.1.0/base/lib:/projects/sems/install/rhel6-x86_64/sems/tpl/yaml_cpp/0.5.3/gcc/4.4.7/base/lib:/projects/sems/install/rhel6-x86_64/sems/tpl/superlu/4.3/gcc/6.1.0/base/lib:/projects/sems/install/rhel6-x86_64/sems/tpl/superlu/4.3/gcc/4.4.7/base/lib:/projects/sems/install/rhel6-x86_64/sems/tpl/parmetis/4.0.3/gcc/6.1.0/openmpi/1.8.7/parallel/lib:/projects/sems/install/rhel6-x86_64/sems/tpl/parmetis/4.0.3/gcc/4.4.7/openmpi/1.8.7/parallel/lib:/projects/sems/install/rhel6-x86_64/sems/tpl/netcdf/4.3.2/gcc/6.1.0/openmpi/1.8.7/parallel/lib:/projects/sems/install/rhel6-x86_64/sems/tpl/netcdf/4.3.2/gcc/4.4.7/openmpi/1.8.7/parallel/lib:/projects/sems/install/rhel6-x86_64/sems/tpl/hdf5/1.8.12/gcc/6.1.0/openmpi/1.8.7/parallel/lib:/projects/sems/install/rhel6-x86_64/sems/tpl/hdf5/1.8.12/gcc/4.4.7/openmpi/1.8.7/parallel/lib:/projects/sems/install/rhel6-x86_64/sems/tpl/zlib/1.2.8/gcc/6.1.0/base/lib:/projects/sems/install/rhel6-x86_64/sems/tpl/zlib/1.2.8/gcc/4.4.7/base/lib:/projects/sems/install/rhel6-x86_64/sems/tpl/boost/1.63.0/gcc/6.1.0/base/lib:/projects/sems/install/rhel6-x86_64/sems/tpl/boost/1.63.0/gcc/4.4.7/base/lib:/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/6.1.0/openmpi/1.8.7/lib:/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/4.4.7/openmpi/1.8.7/lib:/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/6.1.0/base/lib64:/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/6.1.0/base/lib:/projects/sems/install/rhel6-x86_64/sems/utility/git/2.10.1/lib:/projects/sems/install/rhel6-x86_64/sems/utility/cmake/3.5.2/lib:/projects/sems/install/rhel6-x86_64/sems/compiler/python/2.7.9/lib

If I prepend the sems libraries:

export LD_LIBRARY_PATH=/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/6.1.0/openmpi/1.8.7/lib:$LD_LIBRARY_PATH

I can run algebra just fine. I think this will also come up again on cluster builds. Many thanks.

**Comment by ibaned** [comment]
Hi @jwfoulk , I'm going to separate out your issue as #104, lets deal with it over there.

**Pull request merged**
