### PR TITLE
Swap template arguments to Phalanx getFieldData

### PR DESCRIPTION
**Pull request by ibaned**
[#167]

This needs to be merged simultaneously with the corresponding change in Phalanx

### CODE REVIEW

**Comment by rppawlo** [comment]
@ibaned - Thanks for taking care of this! I plan to push this change sometime today when the checkin test script finishes.

**Comment by rppawlo** [comment]
I should have checked on this. Should this be merged at the same time as the changes to phalanx go into the Trilinos/develop branch or do we wait on this merge until the changes make their way into Trilinos/master?

**Comment by rppawlo** [comment]
phalanx changes were pushed...

**Comment by ibaned** [comment]
@rppawlo @lxmota there are tradeoffs...
A lot of Albany's nightly testing uses the Trilinos develop branch.
This has been beneficial due to the very low frequency of Trilinos develop -> master merges.

However, LCM users use Trilinos master.
I think @lxmota will want to wait for this to be in Trilinos master, but if that is taking a long time then I will advocate to merge it now.

**Comment by mperego** [comment]
@ibaned  In general FELIX users (not developers) use Trilinos master as well. So I'm also for holding the merge until the change gets merged in Trilinos master. I guess it is OK if Albany nightly builds linking develop version of Trilinos fail for a few days.

**Comment by lxmota** [comment]
I went ahead and merged this. There was a merge from develop to master in Trilinos that broke tha Albany compilation. In trying to fix this, I discovered than merging this fixes the compile error.

**Pull request merged**
