### PR TITLE
[WIP] Add more flexibility to Fad type choice

### PR DESCRIPTION
**Pull request by jewatkins**
This commit removes the ENABLE_SLFAD and ALBANY_FAST_FELIX config
options and replaces them with the more generic ENABLE_FAD_TYPE
and ENABLE_TAN_FAD_TYPE options. This allows the user to set
the desired Fad type (SFad, SLFad, DFad) for all specializations
or the Tangent, repectively. Sizes are set with ALBANY_SFAD_SIZE,
ALBANY_SLFAD_SIZE, ALBANY_TAN_SFAD_SIZE or ALBANY_TAN_SLFAD_SIZE.

This allows us to deal with issue #330 although the issue still
remains for DFad Tangent on GPUs.

### CODE REVIEW

**Comment by jewatkins** [comment]
Although switching to SLFad seems to fix the GPU bug, @mperego pointed out that DFad should work on the GPU. In fact, the current nightly tests use DFad for all tests. I'll see if I can find a reason why Tangent might break the FELIX sensitivities.

**Comment by agsalin** [comment]
Jerry, we have at least one user, Matt Hoffman at LANL, who builds Trilinos and Albany for ice sheets using the old config options. It gets understandable frustrating for him when Trilinos and/or Albany change options, because he rarely can rebuild without committing to a week of debugging. 

Can you add in some logic in the CMakeLists where it checks for the old config options and throws an error message that clearly tells how to alter the cmake config script to get the same behavior as before? Maybe put a date in the comment so we remember to delete it in a year. Thanks. And Thanks for working to improve the code.

**Comment by ikalash** [comment]
@agsalin : we discussed this with @mperego yesterday at the ProSPect meeting.  I brought up Matt Hoffman as a user too.  Mauro did not think it would be a big deal to communicate to him the new options.  Just in case, my suggestion was to put in logic to throw an error when trying to build with FAST_FELIX on so the user does not accidentally try to use the option if it is removed.  I am fine with your suggestion too.

**Comment by mperego** [comment]
I might be wrong but I don't think Matt is using FAST_FELIX. 
We are slowly try to streamline the process of building MALI, so hopefully this will reduce Matt's and Steve's frustration.
Anyway, I'm fine with your solutions, just thought they were not necessary this time.

**Comment by agsalin** [comment]
Thanks for being on top of it already.

**Comment by jewatkins** [comment]
Thanks for the suggestions everyone. I'll throw an error message for now. We can always clean it up later.

**Comment by jewatkins** [comment]
I'm not sure why 32 is the default. @ikalash do you know?

**Pull request merged**
