### PR TITLE
Interp evaluators

### PR DESCRIPTION
**Pull request by mperego**
This addresses issue #242.

### CODE REVIEW

**Comment by mperego** [comment]
@ikalash would you mind checking whether this branch work fine with CUDA builds?
B.t.w. The speed-up I've noticed using the fast interpolation evaluators over the simpler and safer ones is modest. 5 to 12% for the evaluator which is almost not noticeable for the overall test. I'm wondering if it makes sense to keep the fast implementation around. I guess that with the vectorization of FAD types the speed-up will be reduced even further.

**Comment by ikalash** [comment]
@mperego : sure I'll test this with CUDA and report back the result.

**Comment by ikalash** [comment]
I will test on cuda today.

**Comment by mperego** [comment]
@bartgol @ikalash Thanks!

**Comment by ikalash** [comment]
Sorry for the delay.  I tested this branch on Ride with a CUDA KokkosNode and everything looks good.  In terms of total time for the tests, there is a little bit of a speedup but not much (~4%):

master Total Test time (real) = 1740.86 sec
interpEvaluators Total Test time (real) = 1668.37 sec

**Comment by bartgol** [comment]
Uhm, the master branch should already use the fast interpolation, right? I'm surprised this branch is faster than master...

**Comment by ikalash** [comment]
Doesn't it depend on enabling FAST_FELIX whether the optimizations are used?  Maybe I'm mixing it up with something else.  Anyway, a 4% difference is not significant I would say.  You could run the same branch several times and get these sorts of numbers, depending on, e.g., what else is running.

**Comment by mperego** [comment]
@ikalash Thanks a lot! 
@bartgol Yes, the master branch was already using the fast interpolation. Anyway, let's keep it as is for now, but in the future we might decide to get rid of the fast interpolation evaluators if the speed-up small.

**Pull request merged**
